language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
    - setup-travis
cache:
  directories:
    - node_modules
install:
- npm install -q --no-color --no-progress
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test -- --no-watch --watchAll=false
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
